### ISSUE TITLE
Composer Install: Abandoned Packages

### ISSUE THREAD

**Issue by MBfromOK** [concrete5/composer#51]
While installed Concrete using composer I received the following warnings:
```
Package concrete5/monolog-cascade is abandoned, you should avoid using it. Use concretecms/monolog-cascade instead.
Package dapphp/securimage is abandoned, you should avoid using it. No replacement was suggested.
Package indigophp/hash-compat is abandoned, you should avoid using it. No replacement was suggested.
Package league/url is abandoned, you should avoid using it. Use league/uri instead.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
Package symfony/class-loader is abandoned, you should avoid using it. No replacement was suggested.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
```
Shouldn't the composer process already handle these changes?

**Comment by KorvinSzanto** [comment]
These are things the core requires that are abandoned, itd be better to open an issue against concretecms/concretecms to track on replacijg these things in v10, I know ive opened issues for some of them already.

> Shouldn't the composer process already handle these changes?

Composer can't automatically replace them because some have no replacement and others might have incompatible replacements.

This is safe to ignore for now.
